#
##################################################################
##                           Standard                           ##
##################################################################
#
#Name Name [Type:String] (Unterstützung zufällig)
#
#Material ID [Type:String] (Unterstützung zufällig)
# Beschreibung: Sie können entweder die alte numerische ID oder die englische ID verwenden
# Format-1:
# - 276
# Format-2: 267
#
#Haltbarkeit Durability [Type:String] (Unterstützung zufällig)
# Format-1: 20    Vanilla-Haltbarkeit, "20" entspricht "Die Haltbarkeit des Gegenstands beträgt nur noch (maximale Haltbarkeit des Materials - 20)"
# Format-2: <20   Umgekehrte Berechnung, "<20" bedeutet "Die Haltbarkeit des Gegenstands beträgt nur noch 20"
# Format-3: 20%   Prozentuale Haltbarkeit, entspricht der Haltbarkeitsleiste
# Kann auch unter dem ID-Knoten geschrieben werden ->
# ID:
# - 276:DurabilityFormat
#
#Anzahl Amount [Type:String] (Unterstützung zufällig)
#
#Beschreibung Lore [Type:List] (Unterstützung zufällig)
# Beschreibung: Sie können den /n Zeilenumbruch verwenden
# Format:
# - "..."
#
#Verzauberungsliste EnchantList [Type:List] (Unterstützung zufällig)
# Format:
# - "Verzauberung-Name:Stufe"
# WIKI: https://de.minecraft.wiki/w/Verzauberung#Verzauberungen
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
#Versteckte-Optionen ItemFlagList [Type:List]
# Beschreibung: Wird verwendet, um Attribute, Verzauberungen, unbegrenzte Haltbarkeit, Trankeffekte, Farben und andere Informationen auszublenden
# Format:
# - "HIDE_ENCHANTS"
# - "HIDE_ATTRIBUTES"
# - "HIDE_UNBREAKABLE"
# - "HIDE_POTION_EFFECTS"
# API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
#
#Gegenstand-färben Color [Type:String] (Unterstützung zufällig)
# Beschreibung: Kann verwendet werden, um den Gegenstand zu färben (nur Lederrüstung), hexadezimale Farbcodes erforderlich (ohne #)
# Format: "000000"
#
#Attribut Attributes [Type:List] (Unterstützung zufällig)
# Format:
# - "Attributname:Wert:Modus:Slot"    # Wirkt am aktuellen Slot, für neuere Versionen empfohlen
# - "Attributname:Wert:Modus"         # Wirkt an allen Slots
# Attributnamen:
#   GENERIC_MAX_HEALTH               Maximale Gesundheit
#   GENERIC_FOLLOW_RANGE             Mob-Suchradius
#   GENERIC_KNOCKBACK_RESISTANCE     Rückstoßresistenz
#   GENERIC_MOVEMENT_SPEED           Bewegungsgeschwindigkeit
#   GENERIC_FLYING_SPEED             Fluggeschwindigkeit
#   GENERIC_ATTACK_DAMAGE            Angriffsschaden
#   GENERIC_ATTACK_KNOCKBACK         Angriffs-Rückstoß
#   GENERIC_ATTACK_SPEED             Angriffsgeschwindigkeit
#   GENERIC_ARMOR                    Rüstungsschutz
#   GENERIC_ARMOR_TOUGHNESS          Rüstungshärte
#   GENERIC_LUCK                     Glück (z.B. beim Öffnen von Truhen, Bergbauwagen, Angeln und Monster töten)
#   HORSE_JUMP_STRENGTH              Pferdesprungstärke (nur für Pferderüstung)
#   ZOMBIE_SPAWN_REINFORCEMENTS      Zombie-Verstärkungsfaktor (ungetestet)
# Modi:
#   0   ADD_NUMBER              Addiert/subtrahiert direkt vom Basiswert
#   1   ADD_SCALAR              Wird nach Operation 0 ausgeführt und modifiziert den Multiplikator des Attributwerts, Basis-Multiplikator ist ×1 (keine Änderung)
#   2   MULTIPLY_SCALAR_1       Wird nach allen anderen Modifikatoren (einschließlich anderer Operation 2) ausgeführt, addiert/subtrahiert vom finalen Multiplikator, Basis-Multiplikator ist ×1
# Slots: Wenn kein Slot angegeben wird, wirkt es auf alle Slots
#   HAND      Haupthand
#   OFF_HAND  Zweithand
#   HEAD      Kopf
#   CHEST     Brust
#   LEGS      Beine
#   FEET      Füße
# WIKI: https://de.minecraft.wiki/w/Attribut
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/package-summary.html
#
#Benutzerdefinierte Material-ID CustomModelData: 1000
#
#Trank Potion [Type:Map-?] (Teilweise zufällig)
# Beschreibung: Tranktyp/Dauer/Stärke unterstützen Zufall, Ambient/Partikel/Icon standardmäßig auf true
#              Ich denke, Standard- und benutzerdefinierte Tränke sollten nicht gleichzeitig existieren, daher ist es eine Wahl von einem von beiden. Falsche Trankeffekte werden einfach nicht wirken.
# Format-1:       Standard-Trankparameter
#   Potion: Trankeffekt-ID
#   Potion: <s:JUMP:ABSORPTION>
# Format-2:       Benutzerdefinierter Trank
#   Potion:
#     Statuseffekt-ID:
#       Wirkdauer(duration): 20 # 20=1 Sekunde
#       Stärkestufe(amplifier): 1
#       Atmosphäre(ambient): true
#       Partikeleffekte(particles): true
#       Icon anzeigen(icon): true
#   Potion:
#     <s:SPEED:SLOW>:
#       duration: <c:20 * <i:10_20>>
#       amplifier: <i:1_2>
#
# WIKI: https://de.minecraft.wiki/w/Statuseffekt#Liste_der_Statuseffekte
# API: https://bukkit.windit.net/javadoc/org/bukkit/potion/PotionEffectType.html
#
#Gegenstandsetikett NBT [Type:Map-?] (Unterstützung zufällig)
# Beschreibung: Freie Konfiguration der Informationen unter dem NBT-Knoten im Gegenstand-NBT, kann mit /si nbt angezeigt werden
# Typkonvertierungsbeispiel: (unterstützt nur byte/short/int/long/float/double)
#   key1: '[int]<i:1_100>' # Konvertiert einen Ganzzahl-String von 1-100 in eine Ganzzahl
#   key2: '[double]<d:1_100>' # Konvertiert einen Dezimal-String von 1-100 in eine Dezimalzahl
#
#Gegenstandsdaten: Components [Type:Map] (Unterstützung zufällig)
# Beschreibung: Hochgradig anpassbare Gegenstände, nur 1.20.6+ unterstützt (Plugin für 1.21.1+)
# Format:
#   minecraft:item_name: 'Standardname (kann nicht durch Amboss geändert werden)'
# WIKI: https://de.minecraft.wiki/w/Gegenstandsdaten
#
#Attribute-löschen ClearAttribute [Type:Boolean]
# Beschreibung: Lässt den Gegenstand seine ursprünglichen Standardattribute verlieren
#
#Schutzetikett ProtectNBT [Type:List]
# Beschreibung: Schützt die folgenden NBTs bei automatischen Updates vor Änderungen, kann mit /si nbt angezeigt werden
# Format:
# - "Enchantments" # Schützt Verzauberungseinträge vor automatischen Updates
# - "!protect.data" # Hebt Einträge im globalen Schutz [Config.yml] auf
#
#Lokale-Zufälligkeit Random [Type:Map-?]
# Beschreibung: Festlegen lokaler Zufallsvariablen für den Gegenstand
# Format: Entspricht dem Format im RandomString-Ordner
#
#Automatische-Aktualisierung Update [Type:Boolean]
# Beschreibung: Der Gegenstand wird automatisch aktualisiert (der ursprüngliche Wert von <l:> bleibt erhalten)
#

Default-1:
  Name: <l:Standardpräfix> <l:Standard-Name> <l:<l:Qualität>Color><l:Qualität>
  ID: <l:<l:Beruf>ID>
  Lore:
    - '&6Qualitätsstufe: <l:<l:Qualität>Color><l:Qualität>'
    - '<b:<l:Qualität>:Hervorragend:Episch>&6Berufsbeschränkung: <l:Beruf>'
    - '&6Gegenstandstyp: Hauptwaffe'
    - '&6Einschränkungsstufe: <c:int 10 * <s:<l:Qualität>Basis>>'
    - '&cAngriffskraft: +<l:Angriffskraft>'
    - '<l:Angriff1-10>'
    - '<l:Angriff2-10>'
    - '<l:Angriff3-10>'
    - '<l:Textur>'
    - '<s:<l:Qualität>Edelsteinloch>'
    #   - '&7Haltbarkeit: <c:int <r:300_350> * <s:<l:Qualität>Basis>>/<c:int 400 * <s:<l:Qualität>Basis>>'
    - '&7Haltbarkeit: <c:int <d:0.6_0.9> * <l:Haltbarkeit>>/<l:Haltbarkeit>'
    - '<b:<l:Qualität>:Episch>&cGebunden'
    - '&aAblaufzeit: <t:10m>'
    #   - '&aAblaufzeit: <t:600>'
    - '<b:<l:Qualität>:Hervorragend:Episch>                                    '
    - '<b:<l:Qualität>:Hervorragend:Episch><s:Standard-Lore>'
  EnchantList:
    - <s:<l:Beruf>Verzauberung>
  ClearAttribute: true
  Random:
    Angriffskraft: <c:20 * <s:<l:Qualität>Basis>>
    Haltbarkeit: <c:int <r:350_400> * <s:<l:Qualität>Basis>>
  NBT:
    SX-Attribute.Attribute:
      - 'Eintrag 1'
      - 'SX-Attribute Reservierte Attributschnittstelle'
  ProtectNBT: #Schützt VerzauberungNBT vor Aktualisierungen
    - "Enchantments"
  Update: true

Default-2:
  Name: '&cLeichte Federstiefel'
  ID: LEATHER_BOOTS
  Lore:
    - '&6Gegenstandstyp: Stiefel'
    - '&cLebensobergrenze: +2000'
    - '&dGeschwindigkeit: +50%'
    - '&6Einschränkungsstufe: <r:50_100>'
    - '&r'
    - '&8Geschwindigkeit II'
    - '&cUnterstützt Einzelaktualisierung - (Automatische Aktualisierung)'
    - '&cUnterstützt Einzelabschaltung der Löschmarkierung'
    - '&r'
    - '&eVerkaufspreis: 250'
  EnchantList:
    - DURABILITY:1
  ItemFlagList:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
  Unbreakable: true
  Color: <s:Color>
  Random:
    Color:
      - 'ffffff'
      - '000000'
  Update: true

Default-3:
  Name: '&c&lZufällige Zeichenfolgen Erklärung'
  #Haltbarkeit auf 0 setzen
  ID: 359:<0
  Lore:
    - ''
    - '&4&l!!! Der folgende Inhalt basiert auf Konfiguration dateien !!!'
    - ''
    - "&e&l'&c&l<>&e&l' Nicht ersetzbare Variablen müssen mit ‘&c&l\$&e&l’ maskiert werden"
    - '&7Format: \$<1:Inhalt> oder <Inhalt>'
    - '&7Zum Beispiel: \$<s:Standardpräfix> Oder <Standardpräfix>'
    - ''
    - '&e&lZufälliger Typ:'
    - '&cb   - &7prüfen&r [<b:Übereinstimmender:Wort1:Wort2:Wort3:Wort4>] Diese Zeile wurde gelöscht, weil kein übereinstimmendes Wort und kein übereinstimmender Name vorhanden waren.'
    - '&cb   - &7prüfen&r [<b:<l:Qualität>:Episch:Hervorragend:Gewöhnlich>]'
    - '&ct   - &7Zeitformat&r [<t:1Y1M1D1h1m1s>]'
    - '&cc   - &7Rechner&r [<c:((2*3) + 2) * 1.4>] [<c:int ((2*3) + 2) * 1.4>]'
    - '&cl   - &7sperren&r [<l:Qualität>] [<l:EASY#AAA:BBB:CCC>]'
    - '&cs   - &7Normale&r [<s:<s:Qualität>Color>♦&r] [<s:AAA:BBB:CCC>]'
    - '&cd   - &7Dezimale&r [<d:2.3_6>]'
    - '&ci&7/&cr - &7Ganzzahl&r [<i:1_7>]'
    - '&cu   - &7UUID&r [<u:random>]'
    - '&cj   - &7Skript&r [<j:Default.itemScript#QAQ,QWQ,???,!!!>]'
    - ''
    - "&eLokale Variablen rufen globale Variablen mit ~ auf"
    - "&c ~ &7 in YAML bedeutet &4null"
    - '&7Globale Variablen überschreiben-> <s:Standardpräfix>'
    - '&7Globale und lokale Mischung-> <s:Standard-Lore>'
    - ''
    - 'Nicht vorhandene Variablen löschen die Zeile: <s:Nicht-vorhanden>'
    - '&r↑Hier wurde eine Zeile verschluckt'
  Random:
    Standardpräfix: "Prefix"
    Standard-Lore:
      # 33% Wahrscheinlichkeit zufällig zu Lore, 66% Wahrscheinlichkeit zufällig zu globaler Variable
      - 1: "Lore"
      - 2: ~
  NBT:
    # In den entsprechenden Datentyp umwandeln
    StringConvert:
      byte: "[byte]<s:-128:127>"
      short: "[short]<s:-32768:32767>"
      int: "[int]<s:-2147483648:2147483647>"
      long: "[long]<s:-9223372036854775808:9223372036854775807>"
      float: "[float]<d:-2333_2333>"
      double: "[double]<d:-2333_2333>"

Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7Import-Typ Apfel
      lore:
        - §7Ein Gegenstand vom Typ Import
        - ''
        - §cWie speichert man diesen Typ von Gegenstand?§7
        - ''
        - §7/sx save ID Import
        - ''
        - §cEs unterstützt keine automatische Aktualisierung§7
        - §cZufällige Zeichenfolgen werden nicht unterstützt§7

Default-5:
  Name: '&bLangsames Schwert'
  # YML-Syntax - Anker setzen, nur in dieser Datei gültig
  ID: &def5-ID
    - 268
    - 272
    - 283
    - 267
    - 276
  # Haltbarkeit auf 20% des Maximalwerts setzen
  Durability: 20%
  Lore:
    - '&7Verwenden Sie Attributes, um die ursprüngliche Angriffsgeschwindigkeit einzustellen'
    - ''
    - "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - Werkzeug kann nicht angehoben werden"
  Type: Default
  Update: true
  Attributes:
    - "GENERIC_ATTACK_SPEED:-0.7:1:HAND"
    # - "GENERIC_ATTACK_SPEED:-1:2:HAND"

Default-6:
  Name: "&dKitzelschwert"
  # YML-Syntax - Anker referenzieren, nur in dieser Datei gültig
  ID: *def5-ID
  # Haltbarkeit auf Maximalwert - 30 setzen
  Durability: 30
  Attributes:
    - "GENERIC_ATTACK_DAMAGE:-0.99:2:HAND"

Default-7:
  ID: <l:ID#POTION:SPLASH_POTION:LINGERING_POTION>
  Lore: [ "&cTrank realisiert derzeit nur Version 1.11.1 und höher" ]
  Potion:
    ABSORPTION: &PotionData
      duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
      amplifier: <i:1_3>
      ambient: true
      particles: true
      icon: true
    <s:NIGHT_VISION:BLINDNESS>: *PotionData
    <s:SPEED:SLOW>: *PotionData
    <s:INVISIBILITY:GLOWING:???>: *PotionData
  Random:
    POTION: 1
    SPLASH_POTION: 1
    LINGERING_POTION: 4
  Update: true

Default-8:
  ID: 419
  EnchantList:
    # Bindungsfluch wirkt nicht auf Pferde
    - BINDING_CURSE:1
  Attributes:
    # Bekannt ist, dass Pferde in Version 1.17 Attribute von Pferderüstungen erhalten können. 
    # In Version 1.12.2 und darunter nicht nutzbar, andere Versionen nicht getestet.
    - "HORSE_JUMP_STRENGTH:2:0:CHEST"
    - "GENERIC_MOVEMENT_SPEED:0.5:1:CHEST"

#Default-9: Default-1
Default-9:
  Name: '&9Ersetzbarer Gegenstand'
  ID: '350'
  Lore:
    - ''
    - '&7Ersetze diesen Gegenstand durch Default-1'
    - "&7Verwenden: 'Default-9: Default-1'"
    - ''
    - '&cDas Ziel (Default-1) muss Update aktiviert haben, um ersetzt zu werden'
    - '&4&lErsetzen ist nicht umkehrbar'

#Ist ein gewöhnlicher SX-Item, yml abgekürzt
#Durch die nicht vorhandene ID kann der Gegenstand nicht mehr angezeigt werden, es wird jedoch kein Fehler gemeldet
Default-10.ID: 'Gegenstände, die nicht existieren'

#
##################################################################
##                          Component                           ##
##################################################################
#
Component-1:
  ID: DIAMOND
  Name: "Komponenten-Tutorial"
  Amount: 99
  Lore:
    - "&c该功能为 1.21.1 新增"
    - "&c看到这段文本"
    - "&c代表不支持组件功能"
  #Komponenten
  Components:
    minecraft:item_name: 'Standard-name§8(kann_nicht_durch_Amboss_geändert_werden)'
    minecraft:custom_name: '{"text":"Name der Farbe mit Seltenheit (Amboss modifiziert) § c rot"}'
    # Seltenheit, Färbe priorität unter dem Namen
    minecraft:rarity: 'epic'
    # Maximaler Stapel
    minecraft:max_stack_size: 99
    minecraft:food:
      can_always_eat: true
      eat_seconds: 1.6
      effects: [ ]
      nutrition: 5
      saturation: 10
    minecraft:lore:
      - '{"text":"§aHallo Welt Lores"}'
      - '{"text":"§bDies ist die zweite Zeile"}'
      - '{"text":"§e§lDieser Gegenstand ist essbar"}'
      - '{"text":"§e§lDieser Gegenstand kann Steine abbauen"}'
      - '{"text":"§a§lDieser Gegenstand kann bis zu 99 gestapelt werden"}'
    minecraft:tool:
      rules:
        - blocks:
            - minecraft:stone
          correct_for_drops: true

Component-2:
  ID: 369
  Amount: 50
  Lore:
    - "&cDer essbare Effekt wird nur von 1.12.1 unterstützt"
  Update: true
  Components:
    minecraft:item_name: 'Pommes'
    minecraft:custom_name: 'Pommes'
    minecraft:max_stack_size: 50
    minecraft:rarity: 'rare'
    # 1.21.1
    minecraft:food:
      eat_seconds: 0.1
      nutrition: 1
      saturation: 1
      can_always_eat: true

# Gegenstände oder Dateien mit dem Präfix "NoLoad" werden nicht geladen
NoLoad_Gegenstand:
  ID: 1
  Name: "Nicht geladener Gegenstand"
