#
##################################################################
##                           Standard                           ##
##################################################################
#
#Name Name [Type:String] (Unterstützung zufällig)
#
#Material ID [Type:String] (Unterstützung zufällig)
# Beschreibung: 你可以使用老版数字Id, 也可以使用英文ID
# Format-1:
# - 276
# Format-2: 267
#
#Haltbarkeit Durability [Type:String] (Unterstützung zufällig)
# Format-1: 20    原版耐久，"20" 相当于 "该物品耐久只剩(该材质最大耐久-20)"
# Format-2: <20   反算耐久，"<20" 效果是 "该物品耐久只剩20"
# Format-3: 20%   百分比耐久，与耐久条相同
# 也可以在ID节点下编写->
# ID:
# - 276:DurabilityFormat
#
#Anzahl Amount [Type:String] (Unterstützung zufällig)
#
#Beschreibung Lore [Type:List] (Unterstützung zufällig)
# Beschreibung: 您可以使用 /n 换行符
# Format:
# - "..."
#
#Verzauberungsliste EnchantList [Type:List] (Unterstützung zufällig)
# Format:
# - "Verzauberung-Name:等级"
# WIKI: https://de.minecraft.wiki/w/Verzauberung#Verzauberungen
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
#Versteckte-Optionen ItemFlagList [Type:List]
# Beschreibung: 用于隐藏属性、Verzauberung、无限耐久、药水效果、染色等信息
# Format:
# - "HIDE_ENCHANTS"
# - "HIDE_ATTRIBUTES"
# - "HIDE_UNBREAKABLE"
# - "HIDE_POTION_EFFECTS"
# API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
#
#Gegenstand-färben Color [Type:String] (Unterstützung zufällig)
# Beschreibung: 可以对该物品染色 (仅限皮革防具) ，需要用十六进制Farbe码 (不需要带#)
# Format: "000000"
#
#Attribut Attributes [Type:List] (Unterstützung zufällig)
# Format:
# - "属性名:数字:模式:生效位置"    # 生效当前位置, 高版本推荐使用
# - "属性名:数字:模式"           # 生效所有位置
# 属性名:
#   GENERIC_MAX_HEALTH               最大生命值
#   GENERIC_FOLLOW_RANGE             生物追踪范围
#   GENERIC_KNOCKBACK_RESISTANCE     抗擊退效果
#   GENERIC_MOVEMENT_SPEED           移动速度
#   GENERIC_FLYING_SPEED             飞行速度
#   GENERIC_ATTACK_DAMAGE            攻击伤害
#   GENERIC_ATTACK_KNOCKBACK         击退力度
#   GENERIC_ATTACK_SPEED             攻击速度
#   GENERIC_ARMOR                    盔甲防御点数
#   GENERIC_ARMOR_TOUGHNESS          盔甲韧性
#   GENERIC_LUCK                     幸运度 (例如原版的当打开箱子、运输矿车，钓鱼和杀怪)
#   HORSE_JUMP_STRENGTH              马的弹跳力(只对马铠生效)
#   ZOMBIE_SPAWN_REINFORCEMENTS      僵尸召唤系数(未测试)
# 模式:
#   0   ADD_NUMBER          属性增量    该模式直接在基值上进行加减法操作
#   1   ADD_SCALAR          倍率增量    该模式将在Operation 0之后执行，并直接在属性值的作用倍率上进行加减法操作，也就是将当前的属性值进行倍率上的修改，而基础倍率为×1倍 (即不做改动)
#   2   MULTIPLY_SCALAR_1   最终倍乘    该模式将会在其他所有修饰 (包括其他的Operation 2修饰) 完成后，在最终倍率上执行加减法操作，并执行最终的倍乘。基础倍率同样为×1倍
# 生效位置: 不填写生效位置则生效在所有部位上
#   HAND      主
#   OFF_HAND  副
#   HEAD      头
#   CHEST     身
#   LEGS      腿
#   FEET      脚
# WIKI: https://de.minecraft.wiki/w/Attribut
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/package-summary.html
#
#Benutzerdefinierte Material-ID CustomModelData: 1000
#
#Trank Potion [Type:Map-?] (部分随机)
# 说明: 药水类型/duration/amplifierUnterstützung zufällig, ambient/particles/icon默认值为ture
#      默认和自定义我觉得没有同时存在的必要, 所以是二选一, 药水效果填错只会不生效
# Format-1:       默认药水参数
#   Potion: 药水类型
#   Potion: <s:JUMP:ABSORPTION>
# Format-2:       自定义药水
#   Potion:
#     Statuseffekt-ID:
#       Wirkdauer(duration): 20 # 20=1秒
#       Stärkestufe(amplifier): 1
#       氛围(ambient): true
#       粒子特效(particles): true
#       是否显示图标(icon): true
#   Potion:
#     <s:SPEED:SLOW>:
#       duration: <c:20 * <i:10_20>>
#       amplifier: <i:1_2>
#
# WIKI: https://de.minecraft.wiki/w/Statuseffekt#Liste_der_Statuseffekte
# API: https://bukkit.windit.net/javadoc/org/bukkit/potion/PotionEffectType.html
#
#Gegenstandsetikett NBT [Type:Map-?] (Unterstützung zufällig)
# Beschreibung: 自由的将NBT节点下的配置信息设置到物品NBT中，可输入/si nbt查看
#
#Gegenstandsdaten: Components [Type:Map]
# Beschreibung: 高度自定义物品 仅1.20.6+支持 (插件为1.21.1+)
# Format:
#   minecraft:item_name: '默认名称(无法被铁砧修改)'
# WIKI: https://de.minecraft.wiki/w/Gegenstandsdaten
#
#Attribute-löschen ClearAttribute [Type:Boolean]
# Beschreibung: 让物品失去原有的默认属性
#
#Schutzetikett ProtectNBT [Type:List]
# Beschreibung: 自动更新时保护以下NBT不被更改，可输入/si nbt查看
# Format:
# - "Enchantments" # 保护Verzauberung词条不被自动更新
# - "!protect.data" # 解除在全局保护[Config.yml]中的词条
#
#Lokale-Zufälligkeit Random [Type:Map-?]
# Beschreibung: 设置物品的局部随机变量
# Format: 与RandomString文件夹下的Format一样
#
#Automatische-Aktualisierung Update [Type:Boolean]
# Beschreibung: 会自动更新该物品 (会保留<l:>原本的值)
#

Default-1:
  Name: <l:Standardpräfix> <l:Standard-Name> <l:<l:Qualität>Color><l:Qualität>
  ID: <l:<l:Beruf>ID>
  Lore:
    - '&6Qualitätsstufe: <l:<l:Qualität>Color><l:Qualität>'
    - '<b:<l:Qualität>:Hervorragend:Episch>&6Berufsbeschränkung: <l:Beruf>'
    - '&6Gegenstandstyp: Hauptwaffe'
    - '&6Einschränkungsstufe: <c:int 10 * <s:<l:Qualität>Basis>>'
    - '&cAngriffskraft: +<l:Angriffskraft>'
    - '<l:Angriff1-10>'
    - '<l:Angriff2-10>'
    - '<l:Angriff3-10>'
    - '<l:Textur>'
    - '<s:<l:Qualität>Edelsteinloch>'
    #   - '&7Haltbarkeit: <c:int <r:300_350> * <s:<l:Qualität>Basis>>/<c:int 400 * <s:<l:Qualität>Basis>>'
    - '&7Haltbarkeit: <c:int <d:0.6_0.9> * <l:Haltbarkeit>>/<l:Haltbarkeit>'
    - '<b:<l:Qualität>:Episch>&cGebunden'
    - '&aAblaufzeit: <t:10m>'
    #   - '&aAblaufzeit: <t:600>'
    - '<b:<l:Qualität>:Hervorragend:Episch>                                    '
    - '<b:<l:Qualität>:Hervorragend:Episch><s:Standard-Lore>'
  EnchantList:
    - <s:<l:Beruf>Verzauberung>
  ClearAttribute: true
  Random:
    Angriffskraft: <c:20 * <s:<l:Qualität>Basis>>
    Haltbarkeit: <c:int <r:350_400> * <s:<l:Qualität>Basis>>
  NBT:
    SX-Attribute.Attribute:
      - 'Eintrag 1'
      - 'Eintrag 2'
      - 'Eintrag 3'
      - 'SX-Attribute Reservierte Attributschnittstelle'
  ProtectNBT: #Schützt VerzauberungNBT vor Aktualisierungen
    - "Enchantments"
  Update: true

Default-2:
  Name: '&cLeichte Federstiefel'
  ID: 301
  Lore:
    - '&6Gegenstandstyp: Stiefel'
    - '&cLebensobergrenze: +2000'
    - '&dGeschwindigkeit: +50%'
    - '&6Einschränkungsstufe: <r:50_100>'
    - '&r'
    - '&8Geschwindigkeit II'
    - '&cUnterstützt Einzelaktualisierung - (Automatische Aktualisierung)'
    - '&cUnterstützt Einzelabschaltung der Löschmarkierung'
    - '&r'
    - '&eVerkaufspreis: 250'
  EnchantList:
    - DURABILITY:1
  ItemFlagList:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
  Unbreakable: true
  Color: <s:Color>
  Random:
    Color:
      - 'ffffff'
      - '000000'
  Update: true

Default-3:
  Name: '&c&lZufällige Zeichenfolgen Erklärung'
  #Haltbarkeit auf 0 setzen
  ID: 359:<0
  Lore:
    - ''
    - '&4&l!!! Der folgende Inhalt basiert auf Konfiguration dateien !!!'
    - ''
    - "&e&l'&c&l<>&e&l' Nicht ersetzbare Variablen müssen mit ‘&c&l\$&e&l’ maskiert werden"
    - '&7Format: \$<1:Inhalt> oder <Inhalt>'
    - '&7Zum Beispiel: \$<s:Standardpräfix> Oder <Standardpräfix>'
    - ''
    - '&e&lZufälliger Typ:'
    - '&cb   - &7prüfen&r [<b:Übereinstimmender:Wort1:Wort2:Wort3:Wort4>] Diese Zeile wurde gelöscht, weil kein übereinstimmendes Wort und kein übereinstimmender Name vorhanden waren.'
    - '&cb   - &7prüfen&r [<b:<l:Qualität>:Episch:Hervorragend:Gewöhnlich>]'
    - '&ct   - &7Zeitformat&r [<t:1Y1M1D1h1m1s>]'
    - '&cc   - &7Rechner&r [<c:((2*3) + 2) * 1.4>] [<c:int ((2*3) + 2) * 1.4>]'
    - '&cl   - &7sperren&r [<l:Qualität>] [<l:EASY#AAA:BBB:CCC>]'
    - '&cs   - &7Normale&r [<s:<s:Qualität>Color>♦&r] [<s:AAA:BBB:CCC>]'
    - '&cd   - &7Dezimale&r [<d:2.3_6>]'
    - '&ci&7/&cr - &7Ganzzahl&r [<i:1_7>]'
    - '&cu   - &7UUID&r [<u:random>]'
    - '&cj   - &7Skript&r [<j:Default.itemScript#QAQ,QWQ,???,!!!>]'
    - ''
    - "&eLokale Variablen rufen globale Variablen mit ~ auf"
    - "&c ~ &7 in YAML bedeutet &4null"
    - '&7Globale Variablen überschreiben-> <s:Standardpräfix>'
    - '&7Globale und lokale Mischung-> <s:Standard-Lore>'
    - ''
    - 'Nicht vorhandene Variablen löschen die Zeile: <s:Nicht-vorhanden>'
    - '&r↑Hier wurde eine Zeile verschluckt'
  Random:
    Standardpräfix: "Prefix"
    Standard-Lore:
      # 33% Wahrscheinlichkeit zufällig zu Lore, 66% Wahrscheinlichkeit zufällig zu globaler Variable
      - 1: "Lore"
      - 2: ~

Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7Import-Typ Apfel
      lore:
        - §7Ein Gegenstand vom Typ Import
        - ''
        - §cWie speichert man diesen Typ von Gegenstand?§7
        - ''
        - §7/sx save ID Import
        - ''
        - §cEs unterstützt keine automatische Aktualisierung§7

Default-5:
  Name: '&bLangsames Schwert'
  # YML-Syntax - Anker setzen, nur in dieser Datei gültig
  ID: &def5-ID
    - 268
    - 272
    - 283
    - 267
    - 276
  # Haltbarkeit auf 20% des Maximalwerts setzen
  Durability: 20%
  Lore:
    - '&7Verwenden Sie Attributes, um die ursprüngliche Angriffsgeschwindigkeit einzustellen'
    - ''
    - "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - Werkzeug kann nicht angehoben werden"
  Type: Default
  Update: true
  Attributes:
    - "GENERIC_ATTACK_SPEED:-0.7:1:HAND"
    # - "GENERIC_ATTACK_SPEED:-1:2:HAND"

Default-6:
  Name: "&dKitzelschwert"
  # YML-Syntax - Anker referenzieren, nur in dieser Datei gültig
  ID: *def5-ID
  # Haltbarkeit auf Maximalwert - 30 setzen
  Durability: 30
  Attributes:
    - "GENERIC_ATTACK_DAMAGE:-0.99:2:HAND"

Default-7:
  ID: <l:ID#POTION:SPLASH_POTION:LINGERING_POTION>
  Lore: [ "&cTrank realisiert derzeit nur Version 1.11.1 und höher" ]
  Potion:
    ABSORPTION: &PotionData
      duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
      amplifier: <i:1_3>
      ambient: true
      particles: true
      icon: true
    <s:NIGHT_VISION:BLINDNESS>: *PotionData
    <s:SPEED:SLOW>: *PotionData
    <s:INVISIBILITY:GLOWING:???>: *PotionData
  Random:
    POTION: 1
    SPLASH_POTION: 1
    LINGERING_POTION: 4
  Update: true

Default-8:
  ID: 419
  EnchantList:
    # Bindungsfluch wirkt nicht auf Pferde
    - BINDING_CURSE:1
  Attributes:
    # Bekannt ist, dass Pferde in Version 1.17 Attribute von Pferderüstungen erhalten können. 
    # In Version 1.12.2 und darunter nicht nutzbar, andere Versionen nicht getestet.
    - "HORSE_JUMP_STRENGTH:2:0:CHEST"
    - "GENERIC_MOVEMENT_SPEED:0.5:1:CHEST"

#Default-9: Default-1
Default-9:
  Name: '&9Ersetzbarer Gegenstand'
  ID: '350'
  Lore:
    - ''
    - '&7Ersetze diesen Gegenstand durch Default-1'
    - "&7Verwenden: 'Default-9: Default-1'"
    - ''
    - '&cDas Ziel (Default-1) muss Update aktiviert haben, um ersetzt zu werden'
    - '&4&lErsetzen ist nicht umkehrbar'

#Ist ein gewöhnlicher SX-Item, yml abgekürzt
#Durch die nicht vorhandene ID kann der Gegenstand nicht mehr angezeigt werden, es wird jedoch kein Fehler gemeldet
Default-10.ID: 'Gegenstände, die nicht existieren'

#
##################################################################
##                          Component                           ##
##################################################################
#
Component-1:
  ID: DIAMOND
  Name: "Komponenten-Tutorial"
  Amount: 99
  Lore:
    - "&c该功能为 1.21.1 新增"
    - "&c看到这段文本"
    - "&c代表不支持组件功能"
  #Komponenten
  Components:
    minecraft:item_name: 'Standard-name§8(kann_nicht_durch_Amboss_geändert_werden)'
    minecraft:custom_name: '{"text":"Name der Farbe mit Seltenheit (Amboss modifiziert) § c rot"}'
    # Seltenheit, Färbe priorität unter dem Namen
    minecraft:rarity: 'epic'
    # Maximaler Stapel
    minecraft:max_stack_size: 99
    minecraft:food:
      can_always_eat: true
      eat_seconds: 1.6
      effects: [ ]
      nutrition: 5
      saturation: 10
    minecraft:lore:
      - '{"text":"§aHallo Welt Lores"}'
      - '{"text":"§bDies ist die zweite Zeile"}'
      - '{"text":"§e§lDieser Gegenstand ist essbar"}'
      - '{"text":"§e§lDieser Gegenstand kann Steine abbauen"}'
      - '{"text":"§a§lDieser Gegenstand kann bis zu 99 gestapelt werden"}'
    minecraft:tool:
      rules:
        - blocks:
            - minecraft:stone
          correct_for_drops: true

Component-2:
  ID: 369
  Amount: 50
  Update: true
  Components:
    minecraft:item_name: 'Pommes'
    minecraft:custom_name: 'Pommes'
    minecraft:max_stack_size: 50
    minecraft:rarity: 'rare'
    minecraft:food:
      eat_seconds: 0.1
      nutrition: 1
      saturation: 1
      can_always_eat: true

# Gegenstände oder Dateien mit dem Präfix "NoLoad" werden nicht geladen
NoLoad_Gegenstand:
  ID: 1
  Name: "Nicht geladener Gegenstand"
