#日志等级: [OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL]
LoggerLevel: "ALL"
#浮点数格式化
DecimalFormat: '#.##'
#日期格式化
TimeFormat: yyyy/MM/dd HH:mm
#给予物品时背包满了则掉落
GiveOverflowDrop: true
#史诗怪物掉落的SX物品直接进入玩家背包
MobDropToPlayerInventory: true