name: Foxcraft
main: github.saukiya.foxcraft.Foxcraft
version: ${version}
author: Saukiya
api-version: 1.17
#website:
depend:
  - PlaceholderAPI

softdepend:
  - Multiverse-Core
  - Essentials
  - Residence
  - Vault

commands:
  foxcraft:
    aliases: [fox]

permissions:
  foxcraft.use:
    default: true
  foxcraft.show:
    default: true
  foxcraft.chat:
    default: true
  foxcraft.plugins:
    default: true