name: SX-Item
main: github.saukiya.sxitem.SXItem
version: $version
authors: [ Saukiya, Ray_Hughes, Lounode ]
language: $language
api-version: 1.13
folia-supported: true # SNAPSHOT
website: https://github.com/Saukiya/SX-Item/releases
softdepend:
  - PlaceholderAPI
  - MythicMobs

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

commands:
  SxItem:
    aliases: [ sxi, si ]