name: SX-Item
main: github.saukiya.sxitem.SXItem
version: $version
author: Saukiya
api-version: 1.17
website: https://github.com/Saukiya/SX-Item
depend:
  - PlaceholderAPI

softdepend:
  - Multiverse-Core
  - Essentials
  - Residence
  - Vault

commands:
  sxitem:
    aliases: [ sxi,si ]