#
##################################################################
##                           Default                            ##
##################################################################
#
#Name [Type:String] (Support Random)
#
#ID [Type:String] (Support Random)
# Description: You can use the previous digital ID, or you can use the new ID.
# Format-1:
# - 276
# Format-2: 267
#
#Durability [Type:String] (Support Random)
# Format-1: 20    Default， Equivalent "The material maximum durability - 20"
# Format-2: <20   Reverse， Equivalent "Only 20"
# Format-3: 20%   Percentage， Equivalent "The material maximum durability * 20%"
# YouCanAlsoWriteUnderTheIDNode ->
# ID:
# - 276:Durability
#
#Amount [Type:String] (Support Random)
#
#Lore [Type:List] (Support Random)
# Description: You can use /n line breaks
# Format:
# - "..."
#
#=EnchantList [Type:List] (Support Random)
# Format:
# - "EnchantName:Level"
# WIKI: https://minecraft.wiki/w/Enchanting#Summary_of_enchantments
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
#ItemFlagList [Type:List]
# Description: Used to hide attributes、enchant、unbreakable、effect、color and more.
# Format:
# - "HIDE_ENCHANTS"
# - "HIDE_ATTRIBUTES"
# - "HIDE_UNBREAKABLE"
# - "HIDE_POTION_EFFECTS"
# API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
#
#Color [Type:String] (Support Random)
# Description: can be dyed (leather armor only) ，需要用十六进制AttrColor码 (不需要带#)
# Format: "000000"
#
#Attributes [Type:List] (Support Random)
# Format:
# - "AttributeName:Amount:Operation:Slot"    # Effective current location, higher version recommend use
# - "AttributeName:Amount:Operation"         # Effective all locations
# AttributeName:
#   GENERIC_MAX_HEALTH               
#   GENERIC_FOLLOW_RANGE             
#   GENERIC_KNOCKBACK_RESISTANCE     
#   GENERIC_MOVEMENT_SPEED           
#   GENERIC_FLYING_SPEED             
#   GENERIC_ATTACK_DAMAGE            
#   GENERIC_ATTACK_KNOCKBACK         
#   GENERIC_ATTACK_SPEED             
#   GENERIC_ARMOR                    
#   GENERIC_ARMOR_TOUGHNESS          
#   GENERIC_LUCK                     
#   HORSE_JUMP_STRENGTH              
#   ZOMBIE_SPAWN_REINFORCEMENTS      
# Operation:
#   0   ADD_NUMBER              该模式直接在基值上进行加减法操作
#   1   ADD_SCALAR              该模式将在Operation 0之后执行，并直接在属性值的作用倍率上进行加减法操作，也就是将当前的属性值进行倍率上的修改，而基础倍率为×1倍 (即不做改动)
#   2   MULTIPLY_SCALAR_1       该模式将会在其他所有修饰 (包括其他的Operation 2修饰) 完成后，在最终倍率上执行加减法操作，并执行最终的倍乘。基础倍率同样为×1倍
# Slot: If the effective position is not filled in, it will take effect on all parts.
#   HAND      
#   OFF_HAND  
#   HEAD      
#   CHEST     
#   LEGS      
#   FEET      
# WIKI: https://minecraft.wiki/w/Attribute
# API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/package-summary.html
#
#CustomModelData: 1000
#
#Potion [Type:Map-?] (Support Random)
# Format:
#   Potion:
#     PotionEffectType:
#       duration: 20 # 20=1Seconds
#       amplifier: 1
#       ambient: true
#       particles: true
#       icon: true
#   Potion:
#     <s:SPEED:SLOW>:
#       duration: <c:20 * <i:10_20>>
#       amplifier: <i:1_2>
# WIKI: https://minecraft.wiki/w/Item_format#Potion_Effects
# API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#
#NBT [Type:Map-?] (Support Random)
# Description: Set NBT to item， can use /si nbt
# WIKI: https://minecraft.wiki/w/Item_format#Potion_Effects
#
#ItemComponents: Components [Type:Map-?]
# Support: 1.21.1+
# Description: Highly custom items
# WIKI: https://minecraft.wiki/w/Data_component_format#food
#
#ClearAttribute [Type:Boolean]
# Description: Make items lose their original default attributes
#
#ProtectNBT [Type:List]
# Description: Protect the following NBT from being changed during automatic update， can use /si nbt
# Format:
# - "Enchantments" # Protect 'Enchantments' entries from being automatically updated
# - "!protect.data" # Unprotect entries in global protection 'Config.yml'
#
#Random [Type:Map-?]
# Description: Set the local random variable of the item.
# Format: Same as Format under `RandomString` folder
#
#Update [Type:Boolean]
# Description: The item is auto-update (will retain the original value of <l:>)
#

Default-1:
  Name: <l:DefaultPrefix> <l:DefaultName> <l:<l:Quality>NmColor><l:Quality>
  ID: <l:<l:Occupation>ID>
  Lore:
    - '&6QualityLevel: <l:<l:Quality>NmColor><l:Quality>'
    - '<b:<l:Quality>:Excellent:Epic>&6LimitOccupation: <l:Occupation>'
    - '&6ItemType: MainWeapon'
    - '&6LimitLevel: <c:int 10 * <s:<l:Quality>Base>> Level'
    - '&cAttack: +<l:Attack>'
    - '<l:ATK1-10>'
    - '<l:ATK2-10>'
    - '<l:ATK3-10>'
    - '<l:Texture>'
    - '<s:<l:Quality>GemSlot>'
    #   - '&7Durability: <c:int <r:300_350> * <s:<l:Quality>Base>>/<c:int 400 * <s:<l:Quality>Base>>'
    - '&7Durability: <c:int <d:0.6_0.9> * <l:Durability>>/<l:Durability>'
    - '<b:<l:Quality>:Epic>&cBound'
    - '&aExpiryTime: <t:10m>'
    #   - '&aExpiryTime: <t:600>'
    - '<b:<l:Quality>:Excellent:Epic>                                    '
    - '<b:<l:Quality>:Excellent:Epic><s:DefaultLore>'
  EnchantList:
    - <s:<l:Occupation>Enchant>
  ClearAttribute: true
  Random:
    Attack: <c:20 * <s:<l:Quality>Base>>
    Durability: <c:int <r:350_400> * <s:<l:Quality>Base>>
  NBT:
    SX-Attribute.Attribute:
      - 'Entry 1'
      - 'Entry 2'
      - 'Entry 3'
      - 'SX-Attribute reserved attribute interface'
      - 'If you need to use random, you need to learn advanced random.'
  ProtectNBT: #PROTECT ENCHANT FROM BEING UPDATED
    - "Enchantments"
  Update: true

Default-2:
  Name: '&cLight Feather Boots'
  ID: 301
  Lore:
    - '&6ItemType: Boots'
    - '&cMaxHP: +2000'
    - '&dSpeed: +50%'
    - '&6LimitLevel: <r:50_100>级'
    - '&r'
    - '&8Speed II'
    - '&cSupport single automatic update-(AutoUpdate)'
    - '&cSupport Single Close Clear Labels'
    - '&r'
    - '&eSalePrice: 250'
  EnchantList:
    - DURABILITY:1
  ItemFlagList:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
  Unbreakable: true
  Color: <s:NmColor>
  Random:
    NmColor:
      - 'ffffff'
      - '000000'
  Update: true

Default-3:
  Name: '&c&lRandomStringDescription'
  # Set durability to 0
  ID: 359:<0
  Lore:
    - ''
    - '&4&l!!! The following content is mainly based on configuration files !!!'
    - ''
    - "&e&l'&c&l<>&e&l' Non-Substitute Variables Required '&c&l\$&e&l' Escape"
    - '&7Format: \$<1:Content> 或 <Content>'
    - '&7ForExample: \$<s:DefaultPrefix> 或 <DefaultPrefix>'
    - ''
    - '&e&lRandomType:'
    - '&cb   - &7WholeLineJudgment&r [<b:Match:String1:String2:String3:String4>] This line was deleted because no matching word is the same as the matching name'
    - '&cb   - &7WholeLineJudgment&r [<b:<l:Quality>:Epic:Excellent:Ordinary>]'
    - '&ct   - &7TimeFormat&r [<t:1Y1M1D1h1m1s>]'
    - '&cc   - &7Calculator&r [<c:((2*3) + 2) * 1.4>] [<c:int ((2*3) + 2) * 1.4>]'
    - '&cl   - &7LockRandom&r [<l:Quality>] [<l:EASY#AAA:BBB:CCC>]'
    - '&cs   - &7NormalRandom&r [<s:<s:Quality>NmColor>♦&r] [<s:AAA:BBB:CCC>]'
    - '&cd   - &7DecimalRandom&r [<d:2.3_6>]'
    - '&ci&7/&cr - &7IntegerRandom&r [<i:1_7>]'
    - '&cu   - &7UUIDRandom&r [<u:random>]'
    - '&cj   - &7ScriptProcessing&r [<j:Default.itemScript#QAQ,QWQ,???,!!!>]'
    - ''
    - "&eLocal Variables call Global Variables ~"
    - "&c ~ &7 represents &4null&7 in yml"
    - '&7Override Global Result -> <s:DefaultPrefix>'
    - '&7Global and Local mixed Result -> <s:DefaultLore>'
    - ''
    - 'Variables that do not exist delete the row: <s:DoesNotExist>'
    - '&r↑here s a line that s been eaten'
  Random:
    DefaultPrefix: "Prefix"
    DefaultLore:
      # 33% probability random to Lore, 66% probability random to global variable
      - 1: "Lore"
      - 2: ~

Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7Import type of apple
      lore:
        - §7An item of type Import
        - ''
        - §cHow to save this type of item?§7
        - ''
        - §7/sx save <ItemID> Import
        - ''
        - §cIt does not support automatic updates§7

Default-5:
  Name: '&bSlow Sword'
  # YML syntax-set the anchor point to be valid only in the current file and what else is Google
  ID: &def5-ID
    - 268
    - 272
    - 283
    - 267
    - 276
  # Set durability to maximum * 20%
  Durability: 20%
  Lore:
    - '&7Use Attributes to set the original attack speed'
    - ''
    - "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - Tool will not lift"
  Type: Default
  Update: true
  Attributes:
    - "GENERIC_ATTACK_SPEED:-0.7:1:HAND"
    # - "GENERIC_ATTACK_SPEED:-1:2:HAND"

Default-6:
  Name: "&dTickle Sword"
  # YML Syntax-Reference anchor is valid only within the current file
  ID: *def5-ID
  # Set Endurance to a maximum of -30
  Durability: 30
  Attributes:
    - "GENERIC_ATTACK_DAMAGE:-0.99:2:HAND"

Default-7:
  ID: <l:ID#POTION:SPLASH_POTION:LINGERING_POTION>
  Lore: [ "&cAt present, the potion has only implemented versions 1.11.1 and above." ]
  Potion:
    ABSORPTION: &PotionData
      duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
      amplifier: <i:1_3>
      ambient: true
      particles: true
      icon: true
    <s:NIGHT_VISION:BLINDNESS>: *PotionData
    <s:SPEED:SLOW>: *PotionData
    <s:INVISIBILITY:GLOWING:???>: *PotionData
  Random:
    POTION: 1
    SPLASH_POTION: 1
    LINGERING_POTION: 4
  Update: true

Default-8:
  ID: 419
  EnchantList:
    # Binding Curse does not take effect on horses
    - BINDING_CURSE:1
  Attributes:
    # It is known that 1.17 versions of horses can obtain attributes from horse armor, versions 1.12.2 and below cannot be used, and other versions have not been tested.
    - "HORSE_JUMP_STRENGTH:2:0:CHEST"
    - "GENERIC_MOVEMENT_SPEED:0.5:1:CHEST"

#Default-9: Default-1
Default-9:
  Name: '&9Items that can be replaced'
  ID: '350'
  Lore:
    - ''
    - '&7If you want to replace this item with Default-1'
    - "&7Please use: 'Default-9: Default-1'"
    - ''
    - '&cUpdate for target (Default-1) must be turned on to replace'
    - '&4&lSubstitution is not retroactive'

# Is a Ordinary SX item, yml shorthand
# A non-existent ID will prevent the item from being give out, but it will not report an error.
Default-10.ID: 'Non-existent items'

#
##################################################################
##                          Component                           ##
##################################################################
#
Component-1:
  ID: DIAMOND
  Name: "Component Guide"
  Amount: 99
  Lore:
    - "&cThis function is new for 1.21.1"
    - "&cSeeing this text means that the component function is not supported."
  #组件
  Components:
    minecraft:item_name: "DefaultName§8_(CannotBeModifiedByAnvil)"
    minecraft:custom_name: '{"text":"Name Of Color With Rarity §c(ModifiableByAnvil)"}'
    # Rarity, dye priority lower than name
    minecraft:rarity: 'epic'
    # Maximum Stacking
    minecraft:max_stack_size: 99
    minecraft:food:
      can_always_eat: true
      eat_seconds: 1.6
      effects: [ ]
      nutrition: 5
      saturation: 10
    minecraft:lore:
      - '{"text":"§aHello World lores"}'
      - '{"text":"§bThis is the second line"}'
      - '{"text":"§e§lThis item can be eaten"}'
      - '{"text":"§e§lThis item can collect stones"}'
      - '{"text":"§a§lThis item can be stacked 99"}'
    minecraft:tool:
      rules:
        - blocks:
            - minecraft:stone
          correct_for_drops: true
Component-2:
  ID: 369
  Amount: 50
  Update: true
  Components:
    minecraft:item_name: 'FrenchFries'
    minecraft:custom_name: 'FrenchFries'
    minecraft:max_stack_size: 50
    minecraft:rarity: 'rare'
    minecraft:food:
      eat_seconds: 0.1
      nutrition: 1
      saturation: 1
      can_always_eat: true

# Items prefixed with "NoLoad" will not be loaded
NoLoad_Item:
  ID: 1
  Name: "Items that will not be loaded"
