en:
  Default-1:
    Name: <l:DefaultPrefix>&c炎之洗礼<l:DefaultSuffix> <l:<l:品质>Color><l:品质>
    ID: <l:<l:职业>ID>
    Lore:
      "0": "&6品质等级: <l:<l:品质>Color><l:品质>"
      "1": "<b:<l:品质>:优秀:史诗>&6限制职业: <l:职业>"
      "2": "&6物品类型: 主武器"
      "3": "&6限制等级: <c:int 10 * <s:<l:品质>基数>>级"
      "4": "&c攻击力: +<l:攻击力>"
      "5": <l:攻一-10>
      "6": <l:攻二-10>
      "7": <l:攻三-10>
      "8": <l:纹理>
      "9": <s:<l:品质>宝石孔>
      "10": "&7耐久度: <c:int <d:0.6_0.9> * <l:耐久度>>/<l:耐久度>"
      "11": <b:<l:品质>:史诗>&c已绑定
      "12": "&a到期时间: <t:10m>"
      "13": "<b:<l:品质>:优秀:史诗>                                    "
      "14": <b:<l:品质>:优秀:史诗><s:DefaultLore>
    EnchantList:
      "0": <s:<l:职业>附魔>
    Random:
      攻击力: <c:20 * <s:<l:品质>基数>>
      耐久度: <c:int <r:350_400> * <s:<l:品质>基数>>
    NBT:
      '"SX-Attribute':
        Attribute":
          "0": 词条一
          "1": 词条二
          "2": 词条三
          "3": SX-Attribute预留属性接口
          "4": 如需使用随机则需学习高等随机
    ProtectNBT:
      "0": Enchantments
  Default-2:
    Name: "&c机械轻羽之靴"
    ID: LEATHER_BOOTS
    Lore:
      "0": "&6物品类型: 靴子"
      "1": "&c生命上限: +2000"
      "2": "&d移速增幅: +50%"
      "3": "&6限制等级: <r:50_100>级"
      "4": "&r"
      "5": "&8速度 II"
      "6": "&c支持单项自动更新-(自动更新)"
      "7": "&c支持单项关闭清除标签"
      "8": "&r"
      "9": "&e出售价格: 250"
    EnchantList:
      "0": DURABILITY:1
    ItemFlagList:
      "0": HIDE_ENCHANTS
      "1": HIDE_UNBREAKABLE
    Color: <s:Color>
    Random:
      Color:
        "0": ffffff
        "1": "000000"
  Default-3:
    Name: "&c&l随机字符串说明"
    ID: 359:<0
    Lore:
      "0": ""
      "1": "&4&l!!! 以下内容以配置文件为主 !!!"
      "2": ""
      "3": "&e&l'&c&l<>&e&l' 非替换变量需用 '&c&l\\$&e&l' 转义"
      "4": "&7格式: \\$<1:内容> 或 <内容>"
      "5": "&7例如: \\$<s:DefaultPrefix> 或 <DefaultPrefix>"
      "6": ""
      "7": "&e&l随机类型:"
      "8": "&cb   - &7整行判断&r [<b:匹配名:匹配词1:匹配词2:匹配词3:匹配词4>] 这行因为没有匹配词和匹配名相同而被删除"
      "9": "&cb   - &7整行判断&r [<b:<l:品质>:史诗:优秀:普通>]"
      "10": "&ct   - &7时间格式&r [<t:1Y1M1D1h1m1s>]"
      "11": "&cc   - &7计算器&r [<c:((2*3) + 2) * 1.4>] [<c:int ((2*3) + 2) * 1.4>]"
      "12": "&cl   - &7锁定随机&r [<l:品质>] [<l:EASY#AAA:BBB:CCC>]"
      "13": "&cs   - &7正常随机&r [<s:<s:品质>Color>♦&r] [<s:AAA:BBB:CCC>]"
      "14": "&cd   - &7小数随机&r [<d:2.3_6>]"
      "15": "&ci&7/&cr - &7整数随机&r [<i:1_7>]"
      "16": "&cu   - &7UUID随机&r [<u:random>]"
      "17": "&cj   - &7脚本处理&r [<j:Default.itemScript#QAQ,QWQ,???,!!!>]"
      "18": ""
      "19": "&e局部变量调用全局变量请用 ~"
      "20": "&c ~ &7在 yml 中表示 &4null"
      "21": "&7覆盖全局变量结果-> <s:DefaultPrefix>"
      "22": "&7全局和局部混合结果-> <s:DefaultLore>"
      "23": ""
      "24": "不存在的变量则会删除该行: <s:不存在>"
      "25": "&r↑这里有一行被吃了"
    Random:
      DefaultPrefix: Prefix
      DefaultLore:
        "0":
          "1": Lore
    NBT:
      StringConvert:
        byte: "[byte]<s:-128:127>"
        short: "[short]<s:-32768:32767>"
        int: "[int]<s:-2147483648:2147483647>"
        long: "[long]<s:-9223372036854775808:9223372036854775807>"
        float: "[float]<d:-2333_2333>"
        double: "[double]<d:-2333_2333>"
  Default-4:
    Type: Import
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: APPLE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §7Import类型的苹果
        lore:
          "0": §7一个Type类型为 Import 的物品
          "1": ""
          "2": §c如何保存这种类型的物品?§7
          "3": ""
          "4": §7/sx save 编号 Import
          "5": ""
          "6": §c它不支持自动更新§7
  Default-5:
    Name: "&b慢剑"
    ID:
      "0": "268"
      "1": "272"
      "2": "283"
      "3": "267"
      "4": "276"
    Durability: 20%
    Lore:
      "0": "&7使用Attributes设置原版攻速"
      "1": ""
      "2": "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - 工具将无法抬起"
    Type: Default
    Attributes:
      "0": GENERIC_ATTACK_SPEED:-0.7:1:HAND
  Default-6:
    Name: "&d修脚剑"
    ID:
      "0": "268"
      "1": "272"
      "2": "283"
      "3": "267"
      "4": "276"
    Durability: "30"
    Attributes:
      "0": GENERIC_ATTACK_DAMAGE:-0.99:2:HAND
  Default-7:
    ID: <l:ID#POTION:SPLASH_POTION:LINGERING_POTION>
    Lore:
      "0": "&c药水目前只实现了1.11.1及以上的版本"
    Potion:
      ABSORPTION:
        duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
        amplifier: <i:1_3>
      <s:NIGHT_VISION:BLINDNESS>:
        duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
        amplifier: <i:1_3>
      <s:SPEED:SLOW>:
        duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
        amplifier: <i:1_3>
      <s:INVISIBILITY:GLOWING:???>:
        duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
        amplifier: <i:1_3>
    Random:
      POTION: "1"
      SPLASH_POTION: "1"
      LINGERING_POTION: "4"
  Default-8:
    ID: "419"
    EnchantList:
      "0": BINDING_CURSE:1
    Attributes:
      "0": HORSE_JUMP_STRENGTH:2:0:CHEST
      "1": GENERIC_MOVEMENT_SPEED:0.5:1:CHEST
  Default-9:
    Name: "&9可被替换的物品"
    ID: "350"
    Lore:
      "0": ""
      "1": "&7将此物品替换为Default-1"
      "2": "&7使用: 'Default-9: Default-1'"
      "3": ""
      "4": "&c必须打开目标(Default-1)的Update才可替换"
      "5": "&4&l替换是不可回溯的"
  Default-10:
    ID: 不存在的物品
  Component-1:
    ID: DIAMOND
    Name: 组件教程
    Amount: "99"
    Lore:
      "0": "&c该功能为 1.21.1 新增"
      "1": "&c看到这段文本"
      "2": "&c代表不支持组件功能"
    Components:
      minecraft:item_name: 默认名称(无法被铁砧修改)
      minecraft:custom_name: 带稀有度颜色的名称(可铁砧修改)§c红色
      minecraft:rarity: epic
      minecraft:max_stack_size: "99"
      minecraft:food:
        eat_seconds: "1.6"
        nutrition: "5"
        saturation: "10"
      minecraft:lore:
        "0": '{"text":"§aHello World lores"}'
        "1": '{"text":"§bThis is the second line"}'
        "2": '{"text":"§e§l这个物品可以吃"}'
        "3": '{"text":"§e§l这个物品可以采集石头"}'
        "4": '{"text":"§a§l这个物品可以堆叠99个"}'
      minecraft:tool:
        rules:
          "0":
            blocks:
              "0": minecraft:stone
  Component-2:
    ID: "369"
    Amount: "50"
    Lore:
      "0": "&c食用效果仅 1.12.1 支持"
    Components:
      minecraft:item_name: 薯条
      minecraft:custom_name: 薯条
      minecraft:max_stack_size: "50"
      minecraft:rarity: rare
      minecraft:food:
        eat_seconds: "0.1"
        nutrition: "1"
        saturation: "1"
  NoLoad_Item:
    ID: "1"
    Name: 不会被加载到的物品
