###参数参考链接
#
#EnchantList (支持随机)
# 格式:
# - "附魔名称:等级"
# 参考WIKI: https://minecraft.fandom.com/zh/wiki/%E9%99%84%E9%AD%94
# 参考API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
#ItemFlagList
# 格式:
# - "Flag名"
# 参考API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
#
#Attributes (支持随机)
# 格式:
# - "属性名:数字:模式:生效位置(低版本无视)"
# 属性名:
#   GENERIC_MAX_HEALTH               最大生命值
#   GENERIC_FOLLOW_RANGE             生物追踪范围
#   GENERIC_KNOCKBACK_RESISTANCE     抗擊退效果
#   GENERIC_MOVEMENT_SPEED           移动速度
#   GENERIC_FLYING_SPEED             飞行速度
#   GENERIC_ATTACK_DAMAGE            攻击伤害
#   GENERIC_ATTACK_KNOCKBACK         击退力度
#   GENERIC_ATTACK_SPEED             攻击速度
#   GENERIC_ARMOR                    盔甲防御点数
#   GENERIC_ARMOR_TOUGHNESS          盔甲韧性
#   GENERIC_LUCK                     幸运度（例如原版的当打开箱子、运输矿车，钓鱼和杀怪）
#   HORSE_JUMP_STRENGTH              马的弹跳力(只对马铠生效)
#   ZOMBIE_SPAWN_REINFORCEMENTS      僵尸召唤系数(未测试)
# 模式:
#   0   ADD_NUMBER          属性增量    该模式直接在基值上进行加减法操作
#   1   ADD_SCALAR          倍率增量    该模式将在Operation 0之后执行，并直接在属性值的作用倍率上进行加减法操作，也就是将当前的属性值进行倍率上的修改，而基础倍率为×1倍（即不做改动）
#   2   MULTIPLY_SCALAR_1   最终倍乘    该模式将会在其他所有修饰（包括其他的Operation 2修饰）完成后，在最终倍率上执行加减法操作，并执行最终的倍乘。基础倍率同样为×1倍
# 生效位置: 不填写生效位置则生效在所有部位上
#   HAND      主
#   OFF_HAND  副
#   HEAD      头
#   CHEST     身
#   LEGS      腿
#   FEET      脚
# 参考WIKI: https://minecraft.fandom.com/zh/wiki/%E5%B1%9E%E6%80%A7?variant=zh-cn
# 参考API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/package-summary.html
#

Default-1:
  Name: <s:DefaultPrefix>&c炎之洗礼<s:DefaultSuffix> <s:<l:品质>Color><l:品质>
  ID: <s:<l:职业>ID>
  Lore:
    - '&6品质等级: <s:<l:品质>Color><l:品质>'
    - '<s:<l:品质>职判>&6限制职业: <l:职业>'
    - '&6物品类型: 主武器'
    - '&6限制等级: <c:int 10 * <s:<l:品质>基数>>级'
    - '&c攻击力: +<l:攻击力>'
    - '<l:攻一-10>'
    - '<l:攻二-10>'
    - '<l:攻三-10>'
    - '<l:材质>'
    - '<s:<l:品质>宝石孔>'
    #   - '&7耐久度: <c:int <r:300_350> * <s:<l:品质>基数>>/<c:int 400 * <s:<l:品质>基数>>'
    - '&7耐久度: <c:int <d:0.6_0.9> * <l:耐久度>>/<l:耐久度>'
    - '<s:<l:品质>绑判>&c已绑定'
    - '&a到期时间: <t:10m>'
    #   - '&a到期时间: <t:600>'
    - '<s:<l:品质>介判>                                    '
    - '<s:<l:品质>介判><s:DefaultLore>'
  EnchantList:
    - <s:<l:职业>附魔>
  Unbreakable: false
  ClearAttribute: true
  Random:
    攻击力: <c:20 * <s:<l:品质>基数>>
    耐久度: <c:int <r:350_400> * <s:<l:品质>基数>>
  NBT:
    arg1.arg2: 测试NBT
    sx:
      attribute:
        - '词条一'
        - '词条二'
        - '词条三'
        - 'SX-Attribute预留属性接口'
        - '如需使用随机则需学习高等随机'

Default-2:
  Name: '&c机械轻羽之靴'
  ID: 301
  Lore:
    - '&6物品类型: 靴子'
    - '&c生命上限: +2000'
    - '&d移速增幅: +50%'
    - '&6限制等级: <r:50_100>级'
    - '&r'
    - '&8速度 II'
    - '&c支持单项自动更新-(自动更新)'
    - '&c支持单项关闭清除标签'
    - '&r'
    - '&e出售价格: 250'
  EnchantList:
    - DURABILITY:1
  ItemFlagList:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
  Unbreakable: true
  Color: <s:Color>
  Random:
    Color:
      - 'ffffff'
      - '000000'
  Update: true

Default-3:
  Name: '&c&l随机字符串说明'
  ID: 287
  Lore:
    - ''
    - '&4!!! 以下内容以配置文件为主 !!!'
    - ''
    - "&e&l'<>' 非替换变量需转义"
    - '&7格式: \$<1:内容> 或 <内容>'
    - '&7例如: \$<s:DefaultPrefix> 或 <DefaultPrefix>'
    - ''
    - "&e局部变量调用全局变量请用 ~"
    - "&7' ~ 在 yml 中代表是 &4null'"
    - '&7覆盖全局变量结果-> <s:DefaultPrefix>'
    - '&7全局和局部混合结果-> <s:DefaultLore>'
    - ''
    - '不存在的变量则会删除该行: <s:不存在>'
    - '&r↑这里有一行被吃了'
  Random:
    DefaultPrefix: "Prefix"
    DefaultLore:
      # 2/3的概率随机到Lore，1/3的概率随机到全局变量
      - 2: "Lore"
      - 1: ~

Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      lore:
        - §7一个Type类型为 Import 的物品
        - ''
        - §c如何保存这种类型的物品?§7
        - ''
        - §7/sx save 编号 Import
        - ''
        - §c它不支持自动更新§7

#Default-5: Default-1
Default-5:
  Name: '&c可被替换的物品'
  ID: '350'
  Lore:
    - ''
    - '&7将此物品替换为Default-1'
    - "&7使用: 'Default-5: Default-1'"
    - ''
    - '&c必须打开目标(Default-1)的Update才可替换'
    - '&4&l替换是不可回溯的'

Default-6:
  Name: '&b慢剑'
  # YML语法-设置锚点 仅当前文件内有效 还有啥自己百度
  ID: &def6-ID
    - 268
    - 272
    - 283
    - 267
    - 276
  Lore:
    - '&7使用Attributes设置原版攻速'
    - ''
    - "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - 工具将无法抬起"
  Type: Default
  Update: true
  Attributes:
    - "GENERIC_ATTACK_SPEED:-0.7:1:HAND"
    # - "GENERIC_ATTACK_SPEED:-1:2:HAND"

Default-7:
  Name: "&d修脚剑"
  # YML语法-引用锚点 仅当前文件内有效
  ID: *def6-ID
  Attributes:
    - "GENERIC_ATTACK_DAMAGE:-0.99:2:HAND"

Default-8:
  ID: 419
  EnchantList:
    #绑定诅咒不对马生效
    - BINDING_CURSE:1
  Attributes:
    #属性只对马铠生效，不对马鞍生效
    - "HORSE_JUMP_STRENGTH:2:0:CHEST"
    - "GENERIC_MOVEMENT_SPEED:0.5:1:CHEST"

Default-9:
  ID: '不存在'
  Lore: [ '不存在的ID会使物品无法give出来, 但是不会报错' ]

Default-10:
  Lore: [ '&7没有填ID他就是个苹果' ]

#是个普通的SX物品，yml简写
Default-11.ID: *def6-ID

Default-12:
  ID: [ ]
  Lore: [ 'give了它铁定报错, 因为ID是个空列表' ]